Fix/backprojection
romi/Scan3D pull request #60
Opened 2020-06-17 10:57 UTC by jlegrand62

close #58

2020-06-17 13:05 UTC, naittaleb approved these changes

2020-06-18 14:08 UTC, naittaleb requested changes
Print allocated memory to warn user about possible memory overflow

2020-06-18 14:08 UTC, hanappe commented on romiscan/cl.py
>          self.values_h = self.default_value * \
Print out the sizes of self.shape and the total memory requiements (WxHxPx4 bytes).

2020-06-18 14:09 UTC, hanappe requested changes
Please add a print with the request shape in init_buffer + the total required memory size.

2020-06-19 14:12 UTC, naittaleb approved these changes

2020-06-24 22:08 UTC, merged